### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by sanbroz** [ficiverson/radiocom-flutter#7]
Hi, I am unable to compile the app with Flutter v2.5.3. 
flutter build apk --debug givs following error - 

Because mockito >=4.0.0 <=4.1.1 depends on test_api ^0.2.1 and mockito >=4.1.1+1 <4.1.2 depends on test_api >=0.2.1 <0.4.0, mockito >=4.0.0 <4.1.2 requires test_api >=0.2.1 <0.4.0.
And because mockito >=4.1.2 <=5.0.0-nullsafety.7 depends on test_api ^0.2.19-nullsafety and every version of flutter_test from sdk depends on test_api 0.4.2, flutter_test from sdk is incompatible with mockito >=4.0.0 <=5.0.0-nullsafety.7.
So, because cuacfm depends on both mockito ^4.1.1 and flutter_test any from sdk, version solving failed.
Running "flutter pub get" in v3.2.0...
pub get failed (1; So, because cuacfm depends on both mockito ^4.1.1 and flutter_test any from sdk, version solving
failed.)

**Comment by ficiverson** [comment]
This is because I need to update the dependencies and maybe update a bit the code. Its on my roadmap to update this package in the following weeks. I will keep you posted

**Comment by ficiverson** [comment]
I did a complete update of the dependencies. You can try to build the app now :)
